[package]
name = "openzl-sys"
version = "0.1.0"
edition = "2021"
links = "openzl"
license = "MIT OR Apache-2.0"

[build-dependencies]
cmake = "0.1"
cc = "1.0"
bindgen = "0.69"

[dependencies]
libc = { workspace = true }
